name: tutor_me
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  pie_chart: ^4.0.0
  flutter:
    sdk: flutter
  http: ^0.13.4
  crypt: ^4.2.1
  flutter_time_picker_spinner: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  file_picker: ^4.6.1
  videosdk: ^0.0.10
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.8
  camera: ^0.9.4+5
  flutter_svg: ^1.0.1
  visibility_detector: ^0.2.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3  
  toggle_switch: ^2.0.1
  open_file: ^3.2.1
  email_auth:
  google_fonts: ^3.0.1
  grouped_list: ^4.2.0
  signalr_core: ^1.1.1
  video_player: ^2.4.7
  pigeon: ^1.0.7

  url_launcher: ^6.0.17


  table_calendar: ^3.0.6
  smooth_page_indicator: ^1.0.0+2
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  showcaseview: ^1.1.8


  
dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^1.0.0
  
  flutter_native_splash: ^2.0.1+1

  image_picker: ^0.8.5+3

flutter_native_splash:
  color: "#556268" #lightish green
  image: assets/images/icons/Favicons/favicon-310x310.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/Pictures/
    - .env