name: tutor_me
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_localizations:
    sdk: flutter
  videosdk: ^0.0.10
  flutter_dotenv: ^5.0.2
  cupertino_icons: ^1.0.4
  fluttertoast: ^8.0.8
  camera: ^0.9.4+5
  flutter_svg: ^1.0.1
  visibility_detector: ^0.2.2
  date_time_format: ^2.0.1
  touch_ripple_effect: ^2.2.3

  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  font_awesome_flutter: ^8.10.0
  
  flutter_native_splash: ^2.0.1+1

  image_picker: ^0.8.5+3

flutter_native_splash:
  color: "#556268" #lightish green
  image: assets/images/icons/Favicons/favicon-310x310.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/Pictures/
    - .env