// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using FileSystem.Models;

namespace FileSystem.Data
{
    public partial class FilesContext : DbContext
    {
        public FilesContext()
        {
        }

        public FilesContext(DbContextOptions<FilesContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TuteeFile> TuteeFiles { get; set; }
        public virtual DbSet<TutorFile> TutorFiles { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TuteeFile>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.TuteeImage).HasColumnName("tuteeImage");

                entity.Property(e => e.TuteeTranscript).HasColumnName("tuteeTranscript");
            });

            modelBuilder.Entity<TutorFile>(entity =>
            {
                entity.Property(e => e.Id)
                    .ValueGeneratedNever()
                    .HasColumnName("id");

                entity.Property(e => e.TutorImage).HasColumnName("tutorImage");

                entity.Property(e => e.TutorTranscript).HasColumnName("tutorTranscript");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}