// <auto-generated />
using System;
using FileSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSystem.Migrations
{
    [DbContext(typeof(FilesContext))]
    [Migration("20220914113828_intiMovedApi")]
    partial class intiMovedApi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FileSystem.Models.TuteeFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte[]>("TuteeImage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("tuteeImage");

                    b.Property<byte[]>("TuteeTranscript")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("tuteeTranscript");

                    b.HasKey("Id");

                    b.ToTable("TuteeFiles");
                });

            modelBuilder.Entity("FileSystem.Models.TutorFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte[]>("TutorImage")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("tutorImage");

                    b.Property<byte[]>("TutorTranscript")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("tutorTranscript");

                    b.HasKey("Id");

                    b.ToTable("TutorFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
