// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models
{
    public partial class Module
    {
        public string Code { get; set; }
        public string ModuleName { get; set; }
        public string Institution { get; set; }
        public string Faculty { get; set; }
        public string Year { get; set; }
    }
}