// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Api.Models
{
    public partial class Request
    {
        public string RequesterId { get; set; }
        public string ReceiverId { get; set; }
        public string DateCreated { get; set; }
        public Guid Id { get; set; }
    }
}