// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace TutorMe.Models
{
    public partial class Institution
    {
        public Institution()
        {
            Module = new HashSet<Module>();
            User = new HashSet<User>();
        }

        public Guid InstitutionId { get; set; }
        public string Name { get; set; }
        public string Faculty { get; set; } //TODO : why did I do this? I forgot
        public string Location { get; set; }
        
        
        [JsonIgnore]
        public virtual ICollection<Module> Module { get; set; }
        [JsonIgnore]
        public virtual ICollection<User> User { get; set; }
    }
}