// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileSystem.Models
{
    public partial class TuteeFile
    {
        public Guid Id { get; set; }
        public byte[] TuteeImage { get; set; }
        public byte[] TuteeTranscript { get; set; }
    }
}