// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FileSystem.Models
{
    public partial class TutorFile
    {
        public Guid Id { get; set; }
        public byte[] TutorImage { get; set; }
        public byte[] TutorTranscript { get; set; }
    }
}